
development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "e6f049159561e1e" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "ye6f049159561e1e" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>